Assignment 2
MayaLekova/ios-assignment1 pull request #2
Opened 2017-01-31 08:32 UTC by MayaLekova

Please check if the file structure complies with the MVC idea.

2017-01-31 15:25 UTC, benSmith1981 requested changes
Nice, do the one fix...Maybe in future you can do smaller pull requests 17,000 lines is quite a lot!!

2017-01-31 15:25 UTC, benSmith1981 commented on Assignment1/Assignment1/MovieData.swift
> +                        {
To not have lots of if let if let you can do this (better than lots of indentation
```Swift
if let JSON = response.result.value,
     let jsonObj = JSON.parseJSONString,
     let movieData = jsonObj as? NSDictionary,
     let movieObj = Json4Swift_Base(dictionary: movieData){
       //CODE TO ITERATE MovieObj here
}
```

2017-01-31 15:39 UTC, MayaLekova commented on Assignment1/Assignment1/MovieData.swift
> +                        {
Sorry about the length of the review!

2017-02-03 14:49 UTC, MayaLekova commented
Closing this because the commits are already merged. Fix is applied in next review.

2017-02-03 14:49 UTC, closed without merging